# typings/mlx/__init__.pyi
from typing import Any


class Mlx:
    SYNC_IMAGE_WRITABLE: int
    SYNC_WIN_FLUSH: int
    SYNC_WIN_COMPLETED: int

    def __init__(self) -> None: ...

    # Initialisation
    def mlx_init(self) -> Any: ...
    def mlx_release(self, mlx_ptr: Any) -> int: ...

    # Windows
    def mlx_new_window(self, mlx_ptr: Any, width: int, height: int,
                       title: str) -> Any: ...

    def mlx_clear_window(self, mlx_ptr: Any, win_ptr: Any) -> int: ...
    def mlx_pixel_put(self, mlx_ptr: Any, win_ptr: Any, x: int, y: int,
                      color: int) -> int: ...

    def mlx_destroy_window(self, mlx_ptr: Any, win_ptr: Any) -> int: ...

    # Images
    def mlx_new_image(self, mlx_ptr: Any, width: int, height: int) -> Any: ...

    def mlx_get_data_addr(self, img_ptr: Any) -> tuple[memoryview,
                                                       int, int, int]: ...
    def mlx_put_image_to_window(self, mlx_ptr: Any, win_ptr: Any, img_ptr: Any,
                                x: int, y: int) -> int: ...

    def mlx_destroy_image(self, mlx_ptr: Any, img_ptr: Any) -> int: ...

    # Events & main loop
    def mlx_loop(self, mlx_ptr: Any) -> int: ...
    def mlx_loop_exit(self, mlx_ptr: Any) -> int: ...
    def mlx_mouse_hook(self, win_ptr: Any, callback: Any,
                       param: Any) -> int: ...

    def mlx_key_hook(self, win_ptr: Any, callback: Any, param: Any) -> int: ...

    def mlx_expose_hook(self, win_ptr: Any, callback: Any,
                        param: Any) -> int: ...

    def mlx_loop_hook(self, mlx_ptr: Any, callback: Any,
                      param: Any) -> int: ...

    def mlx_hook(self, win_ptr: Any, x_event: int, x_mask: int, callback: Any,
                 param: Any) -> int: ...

    # Misc.
    def mlx_string_put(self, mlx_ptr: Any, win_ptr: Any, x: int, y: int,
                       color: int, string: str) -> int: ...

    def mlx_xpm_file_to_image(self, mlx_ptr: Any,
                              filename: str) -> tuple[Any, int, int]: ...

    def mlx_png_file_to_image(self, mlx_ptr: Any,
                              filename: str) -> tuple[Any, int, int]: ...

    def mlx_mouse_hide(self, mlx_ptr: Any) -> int: ...
    def mlx_mouse_show(self, mlx_ptr: Any) -> int: ...
    def mlx_mouse_move(self, mlx_ptr: Any, x: int, y: int) -> int: ...
    def mlx_mouse_get_pos(self, mlx_ptr: Any) -> tuple[int, int, int]: ...
    def mlx_do_key_autorepeatoff(self, mlx_ptr: Any) -> int: ...
    def mlx_do_key_autorepeaton(self, mlx_ptr: Any) -> int: ...
    def mlx_get_screen_size(self, mlx_ptr: Any) -> tuple[int, int, int]: ...

    # Sync functions
    def mlx_do_sync(self, mlx_ptr: Any) -> int: ...
    def mlx_sync(self, mlx_ptr: Any, cmd: int, img_or_win_ptr: Any) -> int: ...
